build_image:
    image: docker:stable
    variables:
        DOCKER_HOST: tcp://localhost:2375/
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
        GIT_STRATEGY: fetch

    script:
        - docker build -t wordle-starter .
        - docker run wordle-starter
