build_image:
    image: docker:stable
    services:
        - name: docker:dind

    before_script:
        - docker info

    script:
        - docker build -t wordle-starter .
        - docker run wordle-starter
