build_image:
    image: docker:stable
    variables:
        DOCKER_HOST: unix:///var/run/docker.sock
    services:
        - name: docker:dind

    before_script:
        - docker info

    script:
        - docker build -t wordle-starter .
        - docker run wordle-starter
