image: docker:19.03.12

services:
    - docker:19.03.12-dind

before_script:
    - docker info

build_image:
    script:
        - docker build -t wordle-starter .
        - docker run wordle-starter
