build_image:
    image: docker:stable
    variables:
        DOCKER_HOST: tcp://172.17.0.1:2375/
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
        GIT_STRATEGY: fetch
    services:
        - name: docker:dind


    script:
        - docker build -t wordle-starter .
        - docker run wordle-starter
